WITH C1 AS (
  SELECT PID
  FROM Insurance
  GROUP BY TIV_2015
  HAVING COUNT(*) = 1
), C2 AS (
  SELECT PID
  FROM Insurance
  GROUP BY LAT, LON
  HAVING COUNT(*) = 1
)
SELECT 
  ROUND(SUM(TIV_2016), 2) AS TIV_2016
FROM INSURANCE
WHERE 
  PID NOT IN (SELECT PID FROM C1) AND
  PID IN (SELECT PID FROM C2)