WITH SPENT_TIME AS (
  SELECT 
    SESSION_ID,
    TIMESTAMPDIFF(MINUTE, MIN(EVENT_TIMESTAMP), MAX(EVENT_TIMESTAMP)) AS DIFF
  FROM APP_EVENTS
  GROUP BY SESSION_ID
), SPENT30M AS (
  SELECT SESSION_ID, DIFF
  FROM SPENT_TIME
  WHERE DIFF >= 30
), EVENT_COUNTS AS (
  SELECT 
    SESSION_ID,
    SUM(EVENT_TYPE = 'SCROLL') AS SCROLL,
    SUM(EVENT_TYPE = 'CLICK') AS CLICK
  FROM APP_EVENTS
  GROUP BY SESSION_ID
), SCROLL5 AS (
  SELECT SESSION_ID, SCROLL
  FROM EVENT_COUNTS
  WHERE SCROLL >= 5
), CTS_RATIO AS (
  SELECT 
    SESSION_ID
  FROM EVENT_COUNTS
  WHERE CLICK * 5 < SCROLL
), PURCHASE AS (
  SELECT DISTINCT SESSION_ID
  FROM APP_EVENTS
  WHERE EVENT_TYPE = 'PURCHASE'
)
SELECT 
  DISTINCT E.SESSION_ID, 
  E.USER_ID,
  SP.DIFF AS SESSION_DURATION_MINUTES,
  SC.SCROLL AS SCROLL_COUNT
FROM APP_EVENTS E
JOIN SPENT30M SP
ON E.SESSION_ID = SP.SESSION_ID
JOIN SCROLL5 SC 
ON E.SESSION_ID = SC.SESSION_ID
WHERE 
  E.SESSION_ID IN (SELECT * FROM CTS_RATIO) AND
  E.SESSION_ID NOT IN (SELECT * FROM PURCHASE)
ORDER BY SCROLL_COUNT DESC, SESSION_ID