WITH APPROVED AS (
  SELECT LEFT(TRANS_DATE, 7) AS MONTH, COUNTRY, COUNT(*) AS COUNT, SUM(AMOUNT) AS SUM
  FROM TRANSACTIONS
  WHERE STATE = 'APPROVED'
  GROUP BY LEFT(TRANS_DATE, 7), COUNTRY
),
TOTAL AS (
  SELECT LEFT(TRANS_DATE, 7) AS MONTH, COUNTRY, COUNT(*) AS COUNT, SUM(AMOUNT) AS SUM
  FROM TRANSACTIONS
  GROUP BY LEFT(TRANS_DATE, 7), COUNTRY
)
SELECT 
  T.MONTH,
  T.COUNTRY, 
  T.COUNT AS TRANS_COUNT,
  IFNULL(A.COUNT, 0) AS APPROVED_COUNT,
  T.SUM AS TRANS_TOTAL_AMOUNT,
  IFNULL(A.SUM, 0) AS APPROVED_TOTAL_AMOUNT
FROM TOTAL T
LEFT JOIN APPROVED A
ON T.MONTH = A.MONTH AND (
  T.COUNTRY = A.COUNTRY OR (T.COUNTRY IS NULL AND A.COUNTRY IS NULL)
  )